name: cAdvisor
version: v0.49.1-a
slug: cadvisor
description: Analyzes resource usage and performance characteristics of running containers.
arch:
  - amd64
  - aarch64
url: https://github.com/google/cadvisor
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: expose the metrics endpoint and web UI
webui: http://[HOST]:[PORT:8080]/
docker_api: true
full_access: true
watchdog: http://[HOST]:[PORT:8080]/healthz
image: aaroncarson/hassio-cadvisor-{arch}
options:
  - custom_args: ""
schema:
  - custom_args: "str?"
