name: cAdvisor
version: v0.53.0
slug: cadvisor
description: Analyzes resource usage and performance characteristics of running containers
arch:
  - amd64
  - aarch64
url: https://github.com/google/cadvisor
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: expose the metrics endpoint and web UI
webui: http://[HOST]:[PORT:8080]/
docker_api: true
full_access: true
init: false
watchdog: http://[HOST]:[PORT:8080]/healthz
image: aaroncarson/hassio-cadvisor
options:
  custom_args: ""
schema:
  custom_args: "str?"
privileged:
  - BPF
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME
host_ipc: true
host_dbus: true
