---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:8.1.1
  armhf: ghcr.io/hassio-addons/debian-base/armhf:8.1.1
  armv7: ghcr.io/hassio-addons/debian-base/armv7:8.1.1
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:8.1.1
codenotary:
  base_image: codenotary@frenck.dev

