---
name: Alloy
url: https://github.com/caraar12345/home-assistant-addons/blob/main/promtail
version: v1.10.2-aaroncarson.0
slug: promtail
arch:
  - aarch64
  - amd64
description: Grafana Alloy for Home Assistant
init: false
journald: true
image: ghcr.io/caraar12345/ha-addon-alloy
map:
  - config
  - share
  - ssl
watchdog: http://[HOST]:[PORT:9080]/ready
ports:
  9080/tcp:
ports_description:
  9080/tcp: Alloy web server
options:
  client:
    url: http://39bd2704-loki:3100/loki/api/v1/push
  log_level: info
schema:
  client:
    url: str
    username: str?
    password: password?
    cafile: str?
    servername: str?
    certfile: str?
    keyfile: str?
  additional_pipeline_stages: str?
  additional_scrape_configs: str?
  skip_default_scrape_config: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
