name: Docker build - InfluxDB2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Check for submodule changes
        id: check_submodule
        run: |
          if git diff --quiet HEAD^ HEAD -- influxdb2; then
            echo "No changes in influxdb2 submodule"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in influxdb2 submodule"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Get build metadata
        if: steps.check_submodule.outputs.changed == 'true'
        id: build_metadata
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: ${{ github.workspace }}/influxdb2/influxdb2/config.yaml

      - name: Get current date
        if: steps.check_submodule.outputs.changed == 'true'
        id: date
        run: echo "TODAYS_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        if: steps.check_submodule.outputs.changed == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: steps.check_submodule.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: steps.check_submodule.outputs.changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.check_submodule.outputs.changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/influxdb2/influxdb2
          platforms: linux/amd64 #,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            BUILD_DATE="${{ env.TODAYS_DATE }}"
            BUILD_DESCRIPTION="${{ steps.build_metadata.outputs['description'] }}"
            BUILD_NAME="${{ steps.build_metadata.outputs['name'] }}"
            BUILD_REF="${{ github.sha }}"
            BUILD_REPOSITORY="${{ github.server_url }}/${{ github.repository }}"
            BUILD_VERSION="${{ steps.build_metadata.outputs['version'] }}"
          tags: |
            aaroncarson/ha-addon-influxdb2:latest
            aaroncarson/ha-addon-influxdb2:${{ steps.build_metadata.outputs['version'] }}
            aaroncarson/ha-addon-influxdb2:${{ github.sha }}
