name: Docker build - scanservjs
on:
  push:
    branches:
      - main
    paths:
      - scanservjs/**
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version from config.yml
        id: get_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' scanservjs/config.yml

  build:
    needs: meta
    uses: ./.github/workflows/reusable-docker-build.yml
    secrets: inherit
    with:
      context: ${{ github.workspace }}/scanservjs
      registry: dockerhub
      image: aaroncarson/scanservjs-ha
      version: ${{ needs.meta.outputs.version }}
      platforms: linux/amd64
