name: Docker build - Grafana

on:
  push:
    branches:
      - main
    paths:
      - 'grafana/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: home-assistant/builder@master
        with:
          args: |
            --all
            --target grafana
            --image "ghcr.io/${{ github.repository_owner }}/hass-addon-grafana"
            --docker-user "${{ github.actor }}"
            --docker-password "${{ secrets.GITHUB_TOKEN }}"
