name: Docker build - cAdvisor
on:
  push:
    branches:
      - main
    paths:
      - cadvisor/**
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version from config.yml
        id: get_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' cadvisor/config.yml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./cadvisor
          platforms: linux/amd64,linux/arm64 #,linux/arm/v7
          push: true
          tags: |
            aaroncarson/hassio-cadvisor:latest
            aaroncarson/hassio-cadvisor:${{ steps.get_version.outputs.result }}
            aaroncarson/hassio-cadvisor:${{ github.sha }}