name: Docker build - Alloy
on:
  push:
    branches:
      - main
    paths:
      - 'promtail/**'
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_changes.outputs.changed }}
      version: ${{ steps.build_metadata.outputs.version }}
      description: ${{ steps.build_metadata.outputs.description }}
      name: ${{ steps.build_metadata.outputs.name }}
      build_from: ${{ steps.build_config.outputs['build_from.amd64'] }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- promtail; then
            echo "No changes in promtail directory"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected in promtail directory"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Get build metadata
        if: steps.check_changes.outputs.changed == 'true'
        id: build_metadata
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: ${{ github.workspace }}/promtail/config.yaml

      - name: Get build configuration
        if: steps.check_changes.outputs.changed == 'true'
        id: build_config
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: ${{ github.workspace }}/promtail/build.yaml

      - name: Get current date
        if: steps.check_changes.outputs.changed == 'true'
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  build:
    needs: meta
    if: needs.meta.outputs.changed == 'true'
    uses: ./.github/workflows/reusable-docker-build.yml
    secrets: inherit
    with:
      context: ${{ github.workspace }}/promtail
      registry: ghcr
      image: ghcr.io/${{ github.repository_owner }}/ha-addon-alloy
      version: ${{ needs.meta.outputs.version }}
      build-args: |
        BUILD_FROM=${{ needs.meta.outputs.build_from }}
        BUILD_DATE="${{ needs.meta.outputs.date }}"
        BUILD_DESCRIPTION="${{ needs.meta.outputs.description }}"
        BUILD_NAME="${{ needs.meta.outputs.name }}"
        BUILD_REF="${{ github.sha }}"
        BUILD_REPOSITORY="${{ github.server_url }}/${{ github.repository }}"
        BUILD_VERSION="${{ needs.meta.outputs.version }}"
